### ISSUE TITLE
Can't create monitor on some nodes

### ISSUE THREAD

**Issue by dmekhov** [bokysan/docker-postfix#182]
Hi!
it's strange but some nodes is ok, but other is not

```
2024/02/22 16:14:01 Reading log events from /var/log/mail.log
2024/02/22 16:14:01 Listening on 0.0.0.0:9154
2024/02/22 16:14:01 FATAL -- failed to create Watcher
goroutine 35 [running]:
runtime/debug.Stack()
/usr/local/go/src/runtime/debug/stack.go:24 +0x5e
github.com/nxadm/tail/util.Fatal({0x9dd930?, 0xc0000446c0?}, {0x0, 0x0, 0x0})
/go/pkg/mod/github.com/nxadm/tail@v1.4.8/util/util.go:23 +0x8b
github.com/nxadm/tail/watch.(*InotifyTracker).run(0xc0003ae000)
/go/pkg/mod/github.com/nxadm/tail@v1.4.8/watch/inotify_tracker.go:220 +0x65
created by github.com/nxadm/tail/watch.glob..func1 in goroutine 50
/go/pkg/mod/github.com/nxadm/tail@v1.4.8/watch/inotify_tracker.go:55 +0x14e
```

What can I check?

**Comment by dmekhov** [comment]
Increasing of `fs.inotify.max_user_instances` solve issue
